//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.21 at 03:14:39 PM CST 
//


package org.cyberelay.portal.descriptor.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cyberelay.portal.descriptor.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PortalDef_QNAME = new QName("http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd", "portal-def");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cyberelay.portal.descriptor.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ThemeType }
     * 
     */
    public ThemeType createThemeType() {
        return new ThemeType();
    }

    /**
     * Create an instance of {@link PortletWindowRefType }
     * 
     */
    public PortletWindowRefType createPortletWindowRefType() {
        return new PortletWindowRefType();
    }

    /**
     * Create an instance of {@link PortletContextType }
     * 
     */
    public PortletContextType createPortletContextType() {
        return new PortletContextType();
    }

    /**
     * Create an instance of {@link PortletPaneType }
     * 
     */
    public PortletPaneType createPortletPaneType() {
        return new PortletPaneType();
    }

    /**
     * Create an instance of {@link ContainerPaneType }
     * 
     */
    public ContainerPaneType createContainerPaneType() {
        return new ContainerPaneType();
    }

    /**
     * Create an instance of {@link PortalDefType }
     * 
     */
    public PortalDefType createPortalDefType() {
        return new PortalDefType();
    }

    /**
     * Create an instance of {@link PageType }
     * 
     */
    public PageType createPageType() {
        return new PageType();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link PortletWindowType }
     * 
     */
    public PortletWindowType createPortletWindowType() {
        return new PortletWindowType();
    }

    /**
     * Create an instance of {@link MarkupType }
     * 
     */
    public MarkupType createMarkupType() {
        return new MarkupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortalDefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd", name = "portal-def")
    public JAXBElement<PortalDefType> createPortalDef(PortalDefType value) {
        return new JAXBElement<PortalDefType>(_PortalDef_QNAME, PortalDefType.class, null, value);
    }

}
