//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.21 at 03:14:39 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cyberelay.portal.descriptor.model;
