//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.21 at 03:14:39 PM CST 
//


package org.cyberelay.portal.descriptor.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for portal-defType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="portal-defType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="template" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}templateType" maxOccurs="unbounded"/>
 *         &lt;element name="portlet-context" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}portlet-contextType" maxOccurs="unbounded"/>
 *         &lt;element name="portlet-window" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}portlet-windowType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="page" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}pageType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "portal-defType", propOrder = {
    "template",
    "portletContext",
    "portletWindow",
    "page"
})
public class PortalDefType {

    @XmlElement(required = true)
    protected List<TemplateType> template;
    @XmlElement(name = "portlet-context", required = true)
    protected List<PortletContextType> portletContext;
    @XmlElement(name = "portlet-window")
    protected List<PortletWindowType> portletWindow;
    @XmlElement(required = true)
    protected List<PageType> page;

    /**
     * Gets the value of the template property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the template property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateType }
     * 
     * 
     */
    public List<TemplateType> getTemplate() {
        if (template == null) {
            template = new ArrayList<TemplateType>();
        }
        return this.template;
    }

    /**
     * Gets the value of the portletContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portletContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortletContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortletContextType }
     * 
     * 
     */
    public List<PortletContextType> getPortletContext() {
        if (portletContext == null) {
            portletContext = new ArrayList<PortletContextType>();
        }
        return this.portletContext;
    }

    /**
     * Gets the value of the portletWindow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portletWindow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortletWindow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortletWindowType }
     * 
     * 
     */
    public List<PortletWindowType> getPortletWindow() {
        if (portletWindow == null) {
            portletWindow = new ArrayList<PortletWindowType>();
        }
        return this.portletWindow;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageType }
     * 
     * 
     */
    public List<PageType> getPage() {
        if (page == null) {
            page = new ArrayList<PageType>();
        }
        return this.page;
    }

}
