//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.21 at 03:14:39 PM CST 
//


package org.cyberelay.portal.descriptor.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for portlet-paneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="portlet-paneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="portlet-window" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}portlet-windowType"/>
 *         &lt;element name="portlet-window-ref" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}portlet-window-refType"/>
 *       &lt;/choice>
 *       &lt;attribute name="template-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ordinal" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "portlet-paneType", propOrder = {
    "portletWindow",
    "portletWindowRef"
})
public class PortletPaneType {

    @XmlElement(name = "portlet-window")
    protected PortletWindowType portletWindow;
    @XmlElement(name = "portlet-window-ref")
    protected PortletWindowRefType portletWindowRef;
    @XmlAttribute(name = "template-ref", required = true)
    protected String templateRef;
    @XmlAttribute
    protected Boolean active;
    @XmlAttribute
    protected Integer ordinal;
    @XmlAttribute
    protected String width;

    /**
     * Gets the value of the portletWindow property.
     * 
     * @return
     *     possible object is
     *     {@link PortletWindowType }
     *     
     */
    public PortletWindowType getPortletWindow() {
        return portletWindow;
    }

    /**
     * Sets the value of the portletWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortletWindowType }
     *     
     */
    public void setPortletWindow(PortletWindowType value) {
        this.portletWindow = value;
    }

    /**
     * Gets the value of the portletWindowRef property.
     * 
     * @return
     *     possible object is
     *     {@link PortletWindowRefType }
     *     
     */
    public PortletWindowRefType getPortletWindowRef() {
        return portletWindowRef;
    }

    /**
     * Sets the value of the portletWindowRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortletWindowRefType }
     *     
     */
    public void setPortletWindowRef(PortletWindowRefType value) {
        this.portletWindowRef = value;
    }

    /**
     * Gets the value of the templateRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateRef() {
        return templateRef;
    }

    /**
     * Sets the value of the templateRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateRef(String value) {
        this.templateRef = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the ordinal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrdinal() {
        return ordinal;
    }

    /**
     * Sets the value of the ordinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrdinal(Integer value) {
        this.ordinal = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

}
