//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.21 at 03:14:39 PM CST 
//


package org.cyberelay.portal.descriptor.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for themeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="themeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="root-container-pane" type="{http://www.cyberelay.org/xml/ns/portal/portal-def_1_0.xsd}container-paneType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="template-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "themeType", propOrder = {
    "rootContainerPane"
})
public class ThemeType {

    @XmlElement(name = "root-container-pane", required = true)
    protected ContainerPaneType rootContainerPane;
    @XmlAttribute(name = "template-ref", required = true)
    protected String templateRef;

    /**
     * Gets the value of the rootContainerPane property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerPaneType }
     *     
     */
    public ContainerPaneType getRootContainerPane() {
        return rootContainerPane;
    }

    /**
     * Sets the value of the rootContainerPane property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerPaneType }
     *     
     */
    public void setRootContainerPane(ContainerPaneType value) {
        this.rootContainerPane = value;
    }

    /**
     * Gets the value of the templateRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateRef() {
        return templateRef;
    }

    /**
     * Sets the value of the templateRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateRef(String value) {
        this.templateRef = value;
    }

}
